language: ruby

install:
  - 'travis_retry bundle install'

gemfile:
  - gemfiles/rails3
  - gemfiles/rails4
  - gemfiles/rails41
  - gemfiles/rails42

sudo: false

cache: bundler

script: bundle exec rspec spec